<a href="https://colab.research.google.com/github/penzen/Codes-/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

array_2 = np.arange(1,4)  #similar to range creates an array from 0 to 3
array_o = np.arange(1,4) 

#double ** means power in python 

#np_array crates a numppy array 
print(np.power(np.array([1,2,3]), 4)) #another way to modify using power 
print (array_2 + array_o)




[ 1 16 81]
[2 4 6]


In [ ]:
# common maths oprators 
example = np.arange(1,10)
print(np.negative(example)) #negative output. 
print(np.exp(example))#exponents
print(np.log(example)) #log
print(np.sin(example))#sin
example

[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#multidimentional array 

x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x,y,z], dtype = np.int16) # comblines arrays 
#dtype is used to change the type for memory

print(multi_array)
print(multi_array.shape) #shows 3/3 array shape
print(multi_array[0,2])
print(multi_array.dtype)#prints out type.

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)
2
int16


In [ ]:
 b = np.linspace(1,10,100) # grabes number from 1 to 10 and 100 samples.
print(b)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [ ]:
# slicing 
z = np.arange(1,10)
print(z[1:4:2]) #slicing from index 1 to 4 and the last variable signifnifies a step between numbers 

print(z)

[2 4]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#reshaping 
print (z)
z = np.arange(10).reshape(10,-1) #reshapes a single array into multiple 
#remember that the shape of the array has to match with the number of elements 
# the -1 will put all the data into the specifed amount of rows 
#-1 automates the colom part. 
# z = np.arange(10).reshape(3,3) normal way to do it. 
#z = np.arange(18).reshape(3,3,2) changes into block of arrrays 


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [ ]:
# slcing multidimentional arrays 
print(z)
z[2,1,0]
z[0,1,1]
z[2,1:3,0:3] #slicing multidentional array
z[1, 1 , 1]

print(x[x > 5]) #prints out everything  everything greter than 5

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[]


In [ ]:
z = np.arange(20).reshape(4,-1)
rav = z.ravel() # flatens the array to a single D arry
# ravel changes the original array 
flat = z.flatten() #flatten provides a new copy 
#both ravel and flatten provides the same funtion with diffrence.
print(rav)

#np.resize
#np.t()/ np.transpose()
#np.eye(3) three rows and three coloms sqare shape 
#np.random.rand(4,4) random numbers. 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#matrix multipication 
#the coloms of matrix a should equal to rows of matrix b
#only then can it be multiplied.


mat_a = np.matrix([0,3,5,7,8,9]).reshape(2,3)#two rows three coloms
mat_b = np.matrix([0,3,5,7,8,9]).reshape(3,2)#three rows two coloms 

mat_a * mat_b

matrix([[ 55,  66],
        [112, 158]])